module.exports = [
    'Ableton', 'ActivityPub', 'Actix', 'Adonis', 'AfterEffects', 'AiScript', 'AlpineJS', 'Anaconda', 'AndroidStudio', 'Angular',
    'Ansible', 'Apollo', 'Apple', 'Appwrite', 'Arch', 'Arduino', 'Astro', 'Atom', 'Audition', 'AutoCAD',
    'AWS', 'Azure', 'Babel', 'Bash', 'Bevy', 'BitBucket', 'Blender', 'Bootstrap', 'BSD', 'Bun',
    'C', 'Cassandra', 'CLion', 'Clojure', 'Cloudflare', 'CMake', 'CodePen', 'CoffeeScript', 'CPP', 'Crystal',
    'CS', 'CSS', 'Cypress', 'D3', 'Dart', 'Debian', 'DENO', 'DevTo', 'Discord', 'DiscordBots',
    'DiscordJS', 'Django', 'Docker', 'DotNet', 'DynamoDB', 'Eclipse', 'Elasticsearch', 'Electron', 'Elixir', 'Elysia',
    'Emacs', 'Ember', 'Emotion', 'ExpressJS', 'FastAPI', 'Fediverse', 'Figma', 'Firebase', 'Flask', 'Flutter',
    'Forth', 'Fortran', 'GameMakerStudio', 'Gatsby', 'GCP', 'Gherkin', 'Git', 'Github', 'GithubActions', 'GitLab',
    'Gmail', 'Godot', 'GoLang', 'Gradle', 'Grafana', 'GraphQL', 'GTK', 'Gulp', 'Haskell', 'Haxe',
    'HaxeFlixel', 'Heroku', 'Hibernate', 'HTML', 'Htmx', 'Idea', 'Illustrator', 'Instagram', 'IPFS', 'Java',
    'JavaScript', 'Jenkins', 'Jest', 'JQuery', 'Julia', 'Kafka', 'Kali', 'Kotlin', 'Ktor', 'Kubernetes',
    'Laravel', 'LaTeX', 'Less', 'LinkedIn', 'Linux', 'Lit', 'Lua', 'Markdown', 'Mastodon', 'MaterialUI',
    'Matlab', 'Maven', 'Mint', 'Misskey', 'MongoDB', 'MySQL', 'NeoVim', 'NestJS', 'Netlify',
    'NextJS', 'Nginx', 'Nim', 'Nix', 'NodeJS', 'Notion', 'Npm', 'NuxtJS', 'Obsidian', 'OCaml',
    'Octave', 'OpenCV', 'OpenShift', 'OpenStack', 'p5js', 'Perl', 'Photoshop', 'PHP', 'PhpStorm', 'Pinia',
    'Pkl', 'Plan9', 'PlanetScale', 'Pnpm', 'PostgreSQL', 'Postman', 'Powershell', 'Premiere', 'Prisma', 'Processing',
    'Prometheus', 'Pug', 'PyCharm', 'Python', 'PyTorch', 'QT', 'R', 'RabbitMQ', 'Rails', 'RaspberryPi',
    'React', 'ReactiveX', 'RedHat', 'Redis', 'Redux', 'Regex', 'Remix', 'Replit', 'Rider', 'RobloxStudio',
    'Rocket', 'RollupJS', 'ROS', 'Ruby', 'Rust', 'Sass', 'Scala', 'ScikitLearn', 'Selenium', 'Sentry',
    'Sequelize', 'Sketchup', 'Solidity', 'SolidJS', 'Spring', 'SQLite', 'StackOverflow', 'StyledComponents', 'Sublime', 'Supabase',
    'Svelte', 'SVG', 'Swift', 'Symfony', 'TailwindCSS', 'Tauri', 'TensorFlow', 'Terraform', 'ThreeJS', 'Twitter',
    'TypeScript', 'Ubuntu', 'Unity', 'UnrealEngine', 'V', 'Vala', 'Vercel', 'VIM', 'VisualStudio', 'Vite',
    'Vitest', 'VSCode', 'VSCodium', 'VueJS', 'Vuetify', 'WebAssembly', 'Webflow', 'Webpack', 'WebStorm', 'WindiCSS',
    'Windows', 'Wordpress', 'Workers', 'XD', 'Yarn', 'Yew', 'Zig'
];